implement download_fdz and download_pisa prototypes
beckerbenj/eatFDZ pull request #24
Opened 2024-09-17 13:21 UTC by beckerbenj

For comparing OECD and FDZ data sets, download functions are requested. This is a first implementation of both.

2024-09-17 18:06 UTC, weigtnik requested changes
I think this is a great functionality! I found some relatively minor issues in the code. Apart from that, LGMT!

2024-09-18 12:27 UTC, beckerbenj commented on R/download_pisa.R
> +  #http://r-lib.github.io/progress/
Realized this very late, as the progress bar opens as a separate task in the background with my RStudio setup. Was this different for you?

2024-09-18 12:33 UTC, beckerbenj commented on R/download_pisa.R
> +    data_subdir <- "CY6_MS_CMB_STU_COG.sav"
Fixed, thanks for spotting this!

2024-09-18 12:36 UTC, beckerbenj commented on tests/testthat/test-donwload_pisa.R
> +  expect_equal(nrow(pisa2018), 1)
Fixed, thanks for spotting this!

2024-09-18 12:39 UTC, beckerbenj commented on tests/testthat/test-donwload_pisa.R
> +  skip_if_not(isTRUE(as.logical(Sys.getenv("CI", "false"))))
This line ensures that this test is only executed on the Github Action machines. 

I chose this as the download of the zip-files is rather time consuming and I do not want this done every time I call `devtools::test()` locally. Of course, this has the downside that one might miss some problems with the function locally (as it just happened to me...).

2024-09-18 12:41 UTC, beckerbenj commented on man/download_pisa.Rd
Agree and modified as suggested.

2024-09-18 14:41 UTC, weigtnik commented on R/download_pisa.R
> +  #http://r-lib.github.io/progress/
No, it was the same for me. I only stumbled upon it while Alt+Tab'ing to another window, too.

2024-09-18 14:48 UTC, weigtnik commented on tests/testthat/test-donwload_pisa.R
> +  skip_if_not(isTRUE(as.logical(Sys.getenv("CI", "false"))))
Ah, I see. Thanks for explaining! Maybe, once the other PISA cycles are implemented too, we could test if a data set for one of the years is small enough to be loaded in a reasonable amount of time.

2024-09-18 15:26 UTC, weigtnik approved these changes
Thanks for implementing the requested and suggested changes! LGTM!

FYI: I ran the tests for `download_pisa` on my Windows machine (without lines 6 and 18, of course), and they were successful. 🤷

2024-09-19 08:20 UTC, merged